#!/usr/bin/env python3
"""Theia nightly research-runner (no-agent, autonomous).

Runs every ~12h. Three jobs, all deterministic / API-free on stored data,
fits free-tier budget:
  J1 universe-monitor — count mint-series in the OHLCV cache + forward-corpus
     mints in price_snapshots, so we see data growth week over week.
  J2 re-run batteries — re-run the dip + volume-lowbuy verdict batteries and,
     if a config ever crosses the gate, write a HIT file (the nominal trigger
     to promote / human-review).
  J3 digest — write a dated digest note to the vault so the 24h progress is
     self-documenting even with no one watching.
Mints/keys verified by compute.volume_lowbuy_backtest loader (regression-tested).
"""
from __future__ import annotations

import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, "/home/hermes/project-theia")

from compute import expectancy  # noqa: E402
from compute.dip_reversal_backtest import load_pools  # noqa: E402
from compute.volume_lowbuy_backtest import load_mints, sim_mint  # noqa: E402

OHLCV = Path.home() / ".hermes/theia/wallet_cache/ohlcv"
OUT = Path.home() / ".hermes/theia/wallet_cache/run"  # state shared with nobody; mkdir below
VAULT = Path.home() / "vault/00-Inbox/_knowledge"
HIT_FILE = OUT / "GATE_HIT.json"


def j1_universe() -> dict:
    files = sum(1 for f in OHLCV.iterdir() if f.is_file()) if OHLCV.exists() else 0
    mints = len(load_mints(min_candles=120))
    pools = len(load_pools(min_rows=200))
    return {"ohlcv_files": files, "mints_cached_120c": mints, "pools_200c": pools,
            "ts": int(time.time())}


def _best(lst):
    return max(lst, key=lambda s: s["expectancy"])


def j2_batteries(name: str, report: dict) -> dict:
    # dip-reversal (full universe cache, ROWS-as-signals, ~40k)
    mints = load_mints(min_candles=120)
    # best-config search over a modest grid; report only best
    best = None
    for dip in (0.20, 0.30, 0.40):
        for cf in (0.85, 0.90, 0.95):
            s = [x for r in mints.values() for x in sim_mint(r, dip, cf, 1.30, 120)]
            m = expectancy.evaluate([x["pnl"] for x in s])
            if best is None or m["expectancy"] > best["expectancy"]:
                best = {"rule": "dip_reversal", "dip": dip, "cf": cf, **m}
    report["dip_reversal_best"] = best
    # volume-lowbuy best
    vb = None
    for dip in (0.30, 0.40, 0.50):
        for vm in (2.0, 3.0):
            s = [x for r in mints.values() for x in sim_mint(r, dip, vm, 2.0, 120, require_vol=True)]
            m = expectancy.evaluate([x["pnl"] for x in s])
            if vb is None or m["expectancy"] > vb["expectancy"]:
                vb = {"rule": "volume_lowbuy", "dip": dip, "volx": vm, **m}
    report["volume_lowbuy_best"] = vb
    return report


def j3_digest(report: dict) -> Path:
    VAULT.mkdir(parents=True, exist_ok=True)
    day = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    p = VAULT / f"{day}-nightly-auto-digest.md"
    db = report.get("universe", {})
    lines = [
        f"# Theia nightly auto-digest — {day} (UTC)",
        f"\n_Generated by no-agent research-runner (see `cron/research_runner.py`)._\n",
        f"## Universe growth",
        f"- OHLCV cache files: {db.get('ohlcv_files')}",
        f"- mints (>=120 candles): {db.get('mints_cached_120c')}",
        f"- pools (>=200 candles): {db.get('pools_200c')}",
        "\n## Battery best-config (re-scanned)",
        f"- dip_reversal: {json.dumps(report.get('dip_reversal_best'))}",
        f"- volume_lowbuy: {json.dumps(report.get('volume_lowbuy_best'))}",
        "\n_All expectancy/PF from `compute/expectancy.py`; numbers only, no trading._\n",
    ]
    p.write_text("\n".join(lines))
    return p


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    report: dict = {"ts": int(time.time())}
    try:
        report["universe"] = j1_universe()
    except Exception as e:  # noqa: BLE001
        report["universe_err"] = str(e)
    try:
        report = j2_batteries("", report)
    except Exception as e:  # noqa: BLE001
        report["battery_err"] = str(e)
    try:
        note = j3_digest(report)
        report["digest"] = str(note)
    except Exception as e:  # noqa: BLE001
        report["digest_err"] = str(e)

    # gate HIT check: gate = expectancy>0 AND pf>1 on n>=20
    hits = 0
    for key in ("dip_reversal_best", "volume_lowbuy_best"):
        b = report.get(key)
        if b and b.get("n", 0) >= 20 and b.get("expectancy", 0) > 0 and b.get("profit_factor", 0) > 1:
            hits += 1
    if hits:
        HIT_FILE.parent.mkdir(parents=True, exist_ok=True)
        HIT_FILE.write_text(json.dumps(report, indent=2, default=str))
        print(f"[research] GATE HIT: {hits} rule(s) crossed — see {HIT_FILE}")
    else:
        print("[research] no rule crossed the expectancy/PF gate (n>=20). " +
              json.dumps({k: report.get(k) for k in ('dip_reversal_best', 'volume_lowbuy_best')},
                         default=str))
    print(f"[research] digest -> {report.get('digest')}")


if __name__ == "__main__":
    main()