#!/usr/bin/env bash
# Sync wallet-pipeline scripts from repo (source of truth) to all runtime
# locations. Fix #9: one canonical copy in project-theia/cron, deployed here.
#
#   ./deploy_sync.sh            # dry run
#   ./deploy_sync.sh --apply    # copy files
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "$0")/.." && pwd)"          # project-theia/
APPLY=0; [[ "${1:-}" == "--apply" ]] && APPLY=1

# Runtime locations (order: profile scripts dir is what cron resolves)
PROFILE_SCRIPTS="$HOME/.hermes/profiles/theia/scripts"
HERMES_SCRIPTS="$HOME/.hermes/scripts"
GATE_DIR="$HOME/theia-gate"

# Canonical files in repo/cron
SCRIPTS=(
  wallet_common.py
  wallet_pipeline_v3.py
  wallet_monitor_v2.py
  wallet_report_v2.py
  wallet_discovery_run.py
  discover_wallets.py
  profile_discovered.py
  backtest_cluster.py
)

# Wrappers (generated): pipeline -> v3, monitor -> v2, report -> v2
gen_wrapper() {  # $1 = name  $2 = py target  $3 = py absolute path
  cat <<EOF
#!/bin/bash
# Auto-generated by deploy_sync.sh — run $2 with the venv that has mcp+httpx.
exec /home/hermes/.hermes/theia/mcp/theia-chainrpc/.venv/bin/python "$3"
EOF
}

copy() {  # $1 src  $2 dst
  if [[ $APPLY -eq 1 ]]; then
    mkdir -p "$(dirname "$2")"
    cp "$1" "$2"
  else
    echo "  [dry] $1 -> $2"
  fi
}

echo "== wallet pipeline sync (apply=$APPLY) =="

for f in "${SCRIPTS[@]}"; do
  src="$LOCAL_DIR/cron/$f"
  [[ -f "$src" ]] || { echo "  MISSING $src"; continue; }
  copy "$src" "$PROFILE_SCRIPTS/$f"
  copy "$src" "$HERMES_SCRIPTS/$f"
  copy "$src" "$GATE_DIR/$f"
done

# wrappers point at the profile-scripts .py copies (absolute, cron resolves .sh here)
for pair in "theia-wallet-pipeline.sh:wallet_pipeline_v3.py" \
            "theia-wallet-monitor.sh:wallet_monitor_v2.py" \
            "theia-wallet-report.sh:wallet_report_v2.py" \
            "theia-wallet-discovery.sh:wallet_discovery_run.py"; do
  sh_name="${pair%%:*}"; py_name="${pair##*:}"
  tmp="$(mktemp)"
  gen_wrapper "$sh_name" "$py_name" "$PROFILE_SCRIPTS/$py_name" > "$tmp"
  for dest in "$PROFILE_SCRIPTS" "$HERMES_SCRIPTS"; do
    copy "$tmp" "$dest/$sh_name"
    [[ $APPLY -eq 1 ]] && chmod +x "$dest/$sh_name"
  done
  rm -f "$tmp"
done

echo ""
echo "  note: report wrapper uses chainrpc venv too (has mcp+httpx); report.py is stdlib-only so either venv works."
